MediaFaire/Controllers/AuthencationController.cs
using MediaFaire.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaFaire.Controllers
{

    
    public class AuthencationController : Controller
    {

        private readonly SignInManager<IdentityUser> signInManager;

        private readonly UserManager<IdentityUser> userManager;
        public AuthencationController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)

        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public UserManager<IdentityUser> UserManager { get; }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
     

        [HttpGet("Account/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("Account/Login")]
        public async Task<ActionResult> Login(Login model,string returnUrl)
        {
            
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, true, true);

             
                
                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        return LocalRedirect(returnUrl);
                    }
                        return RedirectToAction("Create", "Uploads");
                }

            }
            return View(model);
        }


        [HttpGet]
        public IActionResult Regestair()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Regestair(Regeister model)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = model.Email,
                    Email = model.Email
                };

               var result = await userManager.CreateAsync(user, model.Password);
               if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, true);
                    return RedirectToAction("Create", "Uploads");
                }else
                {
                    foreach(var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }

                }
                

            }
            return View(model);
        }
        public async Task<IActionResult> LogOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MediaFaire/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization
@inject IViewLocalizer Loc

@{       

    var iRequest = Context.Features.Get<IRequestCultureFeature>();
    var culuter = iRequest.RequestCulture.Culture.Name;
    bool isArbic = culuter == "ar-SA";
}


<!DOCTYPE html>
<html lang="@(isArbic?"ar-SA": "en")">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>B-Hero : Home</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/icon" href="~/assets/images/favicon.ico" />
    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!-- Slick slider -->
    <link href="~/assets/css/slick.css" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="~/assets/css/magnific-popup.css" rel="stylesheet">
    <!-- Skills Circle CSS  -->
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/circlebars@1.0.3/dist/circle.css">


    <!-- Main Style -->
    <link href="~/style.css" rel="stylesheet">

    <!-- Fonts -->
    <!-- Google Fonts Raleway -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,400i,500,500i,600,700" rel="stylesheet">
    <!-- Google Fonts Open sans -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800" rel="stylesheet">

    @if (isArbic)
    {
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
        <link href="~/css/app.rtl.css" rel="stylesheet" />
    }
    <link href="~/css/StyleSheet.css" rel="stylesheet" />


</head>

<body dir="@(isArbic?"rtl": "ltr")">
    <header id="mu-hero">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light mu-navbar">
                <!-- Text based logo -->
                <a class="navbar-brand mu-logo" href="index.html"><span>MEdiaFaire</span></a>
                <!-- image based logo -->
                <!-- <a class="navbar-brand mu-logo" href="index.html"><img src="~/assets/images/logo.png" alt="logo"></a> -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mu-navbar-nav">
                        <li class="nav-item @(Context.Request.Path.Value.ToLower()=="/home/index" ||Context.Request.Path.Value.ToLower()=="/"?"active":"")">
                            <a asp-action="Index" asp-controller="Home">@Loc["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a href="">@Loc["Privacy"]</a>
                        </li>
                        <li class="nav-item  @(Context.Request.Path.Value.ToLower()=="/uploads/browse"?"active":"")">
                            <a asp-controller="Uploads" asp-action="Browse">@Loc["Browes"]</a>
                        </li>
                        <li class="nav-item  @(Context.Request.Path.Value.ToLower()=="/uploads/browse"?"active":"")">
                            <a asp-controller="Home" asp-action="About">@Loc["About"]</a>
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item @(Context.Request.Path.Value.ToLower() == "/authencation/browse" ? "active" : "")">
                                <a asp-area="" asp-controller="Authencation" asp-action="Login">@Loc["Login"]</a>
                            </li>
                            <li class="nav-item @(Context.Request.Path.Value.ToLower() == "/authencation/regestair" ? "active" : "")">
                                <a asp-area="" asp-controller="Authencation" asp-action="Regestair">@Loc["Regestair"]</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item @(Context.Request.Path.Value.ToLower() == "/uploads/index" ? "active" : "")">
                                <a asp-area="" asp-controller="Uploads" asp-action="Index">@Loc["Uploads"]</a>
                            </li>
                            <li class="nav-item @(Context.Request.Path.Value.ToLower() == "/home/contact" ? "active" : "")">
                                <a asp-area="" asp-controller="Home" asp-action="Contact">@Loc["Contact"]</a>
                            </li>
                            <li class="nav-item @(Context.Request.Path.Value.ToLower()=="/authencation/browse"?"active":"")">
                                <div class="text-right">
                                    <a asp-area="">@User.Identity.Name</a>
                                </div>
                            </li>
                            <li class="nav-item @(Context.Request.Path.Value.ToLower()=="/authencation/logout"?"active":"")">
                                <a asp-area="" asp-controller="Authencation" asp-action="LogOut">@Loc["LogOut"]</a>
                            </li>



                        }


                    </ul>
                </div>
            </nav>
        </div>



    </header>




    <div class="container">
        <main class="main-content">
            @RenderBody()
        </main>
    </div>


    <footer id="mu-footer">
        <div class="mu-footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="mu-single-footer">
                            <img class="mu-footer-logo" src="~/assets/images/logo.png" alt="logo">
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus. </p>
                            <div class="mu-social-media">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a class="mu-twitter" href="#"><i class="fa fa-twitter"></i></a>
                                <a class="mu-pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
                                <a class="mu-google-plus" href="#"><i class="fa fa-google-plus"></i></a>
                                <a class="mu-youtube" href="#"><i class="fa fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mu-single-footer">
                            <h3>Twitter feed</h3>
                            <ul class="list-unstyled">
                                <li class="media">
                                    <span class="fa fa-twitter"></span>
                                    <div class="media-body">
                                        <a href="#">2 hours ago</a>
                                    </div>
                                </li>
                                <li class="media">
                                    <span class="fa fa-twitter"></span>
                                    <div class="media-body">
                                        <a href="#">2 hours ago</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mu-single-footer">

                            <h3>Languages</h3>
                            <ul class="mu-useful-links">
                                <li><a href="/Home/SetLang?Lang=ar-SA&returnUrl=@Context.Request.Path.Value">العربيه</a></li>
                                <li><a href="/Home/SetLang?Lang=en-US">English</a></li>

                            </ul>


                            <h3>Useful link</h3>
                            <ul class="mu-useful-links">
                                <li><a href="#">Help Center</a></li>
                                <li><a href="#">Download Center</a></li>
                                <li><a href="#">User Account</a></li>
                                <li><a href="#">Support Forum</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="mu-single-footer">
                            <h3>Contact Information</h3>
                            <ul class="list-unstyled">
                                <li class="media">
                                    <span class="fa fa-home"></span>
                                    <div class="media-body">
                                        <p>349 Main St, Deseronto, ON K0K 1X0, Canada</p>
                                    </div>
                                </li>
                                <li class="media">
                                    <span class="fa fa-phone"></span>
                                    <div class="media-body">
                                        <p>+00 123 456 789 00</p>
                                        <p>+ 00 254 632 548 00</p>
                                    </div>
                                </li>
                                <li class="media">
                                    <span class="fa fa-envelope"></span>
                                    <div class="media-body">
                                        <p>support@bhero.com</p>
                                        <p>help.behero@gmail.com</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mu-footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="mu-footer-bottom-area">
                            <p class="mu-copy-right">&copy; Copyright <a rel="nofollow" href="http://markups.io">markups.io</a>. All right reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>